%enhance images
imageAugmenter = imageDataAugmenter( ...
    'RandXReflection', true, ...
    'RandRotation',[-6, 6], ...
    'RandXTranslation',[-4 4], ...
    'RandYTranslation',[-4 4]);

%%split data into training set and testing set
[imdsTrain,imdsTest] = splitEachLabel(imds,0.8); 

%scaling images
augimdsTrain=augmentedImageDatastore([224, 224, 3],imdsTrain, 'ColorPreprocessing', 'gray2rgb','DataAugmentation',imageAugmenter);
augimdsTest=augmentedImageDatastore([224, 224, 3],imdsTest, 'ColorPreprocessing', 'gray2rgb');

options = trainingOptions('adam', ...
    'MaxEpochs',8,...
    'MiniBatchSize',16, ...
    'VerboseFrequency',200, ...
    'InitialLearnRate',1e-4, ...
    'Shuffle','every-epoch', ...
    'Plots','training-progress', ...
    'LearnRateSchedule' , 'piecewise', ...
    'LearnRateDropPeriod', 16, ...
    'LearnRateDropFactor', 0.9, ...
    'ValidationData', augimdsTest, ...
    'ValidationFrequency', 200, ...
    'ExecutionEnvironment','gpu');

net = trainNetwork(augimdsTrain,lgraph_1,options);
