%%enhance images
imageAugmenter = imageDataAugmenter( ...
    'RandXReflection', true, ...
    'RandRotation',[-10,10], ...
    'RandXTranslation',[-8 8], ...
    'RandYTranslation',[-8 8]);

%%split data into training set and testing set
[imdsTrain,imdsTest] = splitEachLabel(imds,0.9); 

%scaling images
augimdsTrain=augmentedImageDatastore([224, 224, 3],imdsTrain, 'ColorPreprocessing', 'gray2rgb','DataAugmentation',imageAugmenter);
augimdsTest=augmentedImageDatastore([224, 224, 3],imdsTest, 'ColorPreprocessing', 'gray2rgb');

options = trainingOptions('adam', ...
    'MaxEpochs',50,...
    'MiniBatchSize',32, ...
    'VerboseFrequency',20000, ...
    'InitialLearnRate',1e-4, ...
    'Shuffle','every-epoch', ...
    'Plots','training-progress', ...
    'LearnRateSchedule' , 'piecewise', ...
    'LearnRateDropPeriod', 6, ...
    'LearnRateDropFactor', 0.9, ...
    'ValidationData', augimdsTest, ...
    'ValidationFrequency', 20000, ...
    'CheckpointPath', 'E:\temp_net', ...
    'ExecutionEnvironment','gpu');

net = trainNetwork(augimdsTrain,lgraph_1,options);
